# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
   https://colab.research.google.com/drive/1LOy7v4lAWu9SLhRpkLye7w_vvnCsFATY
"""

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

import pandas as pd
data=pd.read_csv("Salaries.csv")
data

exp=data["yrs.service"]
exp

salary=data["salary"]
salary

model=LinearRegression()

x=np.array(exp).reshape(-1,1)
y=np.array(salary).reshape(-1,1)

x
y
model.fit(x,y)

expirence=int(input("Enter your experience:"))
new_data=np.array(expirence).reshape(-1,1)
y_answer=model.predict(new_data)
print("Your salary is:",model.predict(new_data))

Enter your experience:2
Your salary is: [[101533.79109372]]

import matplotlib.pyplot as plt
plt.plot(x,y)
plt.scatter(new_data,y_answer)
plt.xlabel("Experience")
plt.ylabel("Salary")
plt.title("Salary vs Experience")
plt.show()
