# -*- coding: utf-8 -*-
"""Multilinear_Regression.ipynb

Automatically generated by Colab.

Original file is located at
   https://colab.research.google.com/drive/1KbqgRGyfhowSC0Ajh0mqutHWqVKuRk7W
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score
from mpl_toolkits.mplot3d import Axes3D

df = pd.read_csv("salary_data.csv")
df

print(df.head())

print("\nMissing Values")
print(df.isnull().sum())

df.dropna(inplace=True)

print("\nDataset Shape :", df.shape)

df["EducationLevel"] = df["EducationLevel"].map(education_mapping)

x2=df.fillna(df['EducationLevel'].mean())
x2

x=df.loc[1:20,'YearsExperience']
x1=x.fillna(x.mean())
x1

x2=df.loc[1:20,'EducationLevel']
x2

X=np.column_stack((x1,x2))
X

import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(
    df["EducationLevel"],
    df["YearsExperience"],
    df["Salary"]
)
ax.set_title(
    "EducationLevel vs YearsExperience vs Salary"
)
ax.set_xlabel("Education Level")
ax.set_ylabel("Years Experience")
ax.set_zlabel("Salary")
plt.show()

y=df.loc[1:20,'EducationLevel']
y=y.fillna(y.mean())
y=np.array(y).reshape(-1,1)
y
